import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import SessionProvider from '../components/SessionProvider';
import { getServerSession } from "next-auth";
import "./globals.css";
export const metadata = {
  title: "Babur Hat",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className="">
        <main>
          <SessionProvider session={session}>
            {children}
          </SessionProvider>
        </main>
        <ToastContainer position="top-center"
          autoClose={2000} theme="dark" />
      </body>
    </html>
  );
}
