import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
export const metadata = {
  title: "Babur Hat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <main>{children}</main>
        <ToastContainer position="top-center"
          autoClose={2000} theme="dark" />
      </body>
    </html>
  );
}
